FROM java:8-jre

ENV CATALINA_HOME /opt/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH

RUN mkdir -p "$CATALINA_HOME"
WORKDIR $CATALINA_HOME

ENV TOMCAT_MAJOR 8
ENV TOMCAT_VERSION 8.5.34

ENV URL https://www.apache.org/dist/tomcat/tomcat-"$TOMCAT_MAJOR"/v"$TOMCAT_VERSION"/bin/apache-tomcat-"$TOMCAT_VERSION".tar.gz

ENV PATH_WAR build/libs/TollAPI.war
RUN curl -O "$URL" 
RUN tar xzvf apache-tomcat-8.5.34.tar.gz --strip-components=1

COPY "$PATH_WAR" /opt/tomcat/webapps/TollAPI.war

EXPOSE 8080
CMD ["catalina.sh", "run"]
	
