FROM java:8-jre

ENV CATALINA_HOME /opt/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH

RUN mkdir -p "$CATALINA_HOME"
WORKDIR $CATALINA_HOME

ENV URL https://www.apache.org/dist/tomcat/tomcat-8/v8.5.34/bin/apache-tomcat-8.5.34.tar.gz

ENV PATH build/libs/TollAPI.war
RUN curl -O "$URL" 
RUN tar xzvf apache-tomcat-8.5.34.tar.gz --strip-components=1

COPY "$PATH" /opt/tomcat/webapps/TollAPI.war

EXPOSE 8080
CMD ["catalina.sh", "run"]
	
